name: Delete Merged Feature Branches

on:
  push:
    branches:
      - main

jobs:
  delete-merged-feature-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener el historial complete          

      - name: Clean-up merged feature branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          
          # Expresión regular para filtrar ramas que sigan el patrón específico
          regexBranchPattern="feature-E-[0-9]+-.*"
          echo "$RESULTADO_JSON" | jq -r '.items[].path' | grep -P "$regexBranchPattern"

          # Obtener las ramas fusionadas en main
          MERGED_BRANCHES=$(git branch -a --format "%(refname:short) %(upstream)" | awk '$2 !~/\/origin\// { print $1 }'")

          # Filtrar solo las que cumplan con el patrón
          FILTERED_BRANCHES=$(echo "$MERGED_BRANCHES" | grep -E "$regexBranchPatter" || true)

          if [[ -z "$FILTERED_BRANCHES" ]]; then
            echo "No merged feature branches to delete."
            exit 0
          fi

          echo "Deleting merged feature branches:"
          echo "$FILTERED_BRANCHES"

          for BRANCH in $FILTERED_BRANCHES; do
            git push origin --delete $BRANCH
          done